<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyName>TechMartProductManager</AssemblyName>
    <RootNamespace>TechMartProductManager</RootNamespace>
    <StartupObject>TechMartProductManager.Program</StartupObject>
  </PropertyGroup>

</Project>
